<!DOCTYPE html>
<head>

</head>
<body>

	<br />
	<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
			<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: quoted_printable_encode() expects parameter 1 to be string, array given in /home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/ContentEncoder/NativeQpContentEncoder.php on line <i>95</i></th></tr>
			<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
			<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
			<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>248800</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/kkeller13/public_html/bread-basket/public_html/php/controllers/contact-form-controller.php' bgcolor='#eeeeec'>.../contact-form-controller.php<b>:</b>0</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0142</td><td bgcolor='#eeeeec' align='right'>1250408</td><td bgcolor='#eeeeec'>Swift_Mailer->send(  )</td><td title='/home/kkeller13/public_html/bread-basket/public_html/php/controllers/contact-form-controller.php' bgcolor='#eeeeec'>.../contact-form-controller.php<b>:</b>79</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0159</td><td bgcolor='#eeeeec' align='right'>1283080</td><td bgcolor='#eeeeec'>Swift_Transport_AbstractSmtpTransport->send(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php' bgcolor='#eeeeec'>.../Mailer.php<b>:</b>85</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0162</td><td bgcolor='#eeeeec' align='right'>1292912</td><td bgcolor='#eeeeec'>Swift_Transport_AbstractSmtpTransport->_sendTo(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php' bgcolor='#eeeeec'>.../AbstractSmtpTransport.php<b>:</b>176</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.0162</td><td bgcolor='#eeeeec' align='right'>1293368</td><td bgcolor='#eeeeec'>Swift_Transport_AbstractSmtpTransport->_doMailTransaction(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php' bgcolor='#eeeeec'>.../AbstractSmtpTransport.php<b>:</b>444</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.0174</td><td bgcolor='#eeeeec' align='right'>1293760</td><td bgcolor='#eeeeec'>Swift_Transport_AbstractSmtpTransport->_streamMessage(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php' bgcolor='#eeeeec'>.../AbstractSmtpTransport.php<b>:</b>428</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.0175</td><td bgcolor='#eeeeec' align='right'>1298552</td><td bgcolor='#eeeeec'>Swift_Message->toByteStream(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php' bgcolor='#eeeeec'>.../AbstractSmtpTransport.php<b>:</b>327</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.0175</td><td bgcolor='#eeeeec' align='right'>1298680</td><td bgcolor='#eeeeec'>Swift_Mime_SimpleMessage->toByteStream(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php' bgcolor='#eeeeec'>.../Message.php<b>:</b>172</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.0181</td><td bgcolor='#eeeeec' align='right'>1307488</td><td bgcolor='#eeeeec'>Swift_Mime_SimpleMimeEntity->toByteStream(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php' bgcolor='#eeeeec'>.../SimpleMessage.php<b>:</b>608</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.0211</td><td bgcolor='#eeeeec' align='right'>1311632</td><td bgcolor='#eeeeec'>Swift_Mime_SimpleMimeEntity->_bodyToByteStream(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php' bgcolor='#eeeeec'>.../SimpleMimeEntity.php<b>:</b>532</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.0215</td><td bgcolor='#eeeeec' align='right'>1314272</td><td bgcolor='#eeeeec'>Swift_Mime_SimpleMimeEntity->toByteStream(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php' bgcolor='#eeeeec'>.../SimpleMimeEntity.php<b>:</b>572</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.0216</td><td bgcolor='#eeeeec' align='right'>1314616</td><td bgcolor='#eeeeec'>Swift_Mime_SimpleMimeEntity->_bodyToByteStream(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php' bgcolor='#eeeeec'>.../SimpleMimeEntity.php<b>:</b>532</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>0.0217</td><td bgcolor='#eeeeec' align='right'>1315112</td><td bgcolor='#eeeeec'>Swift_Mime_ContentEncoder_QpContentEncoderProxy->encodeString(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php' bgcolor='#eeeeec'>.../SimpleMimeEntity.php<b>:</b>559</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>0.0217</td><td bgcolor='#eeeeec' align='right'>1315112</td><td bgcolor='#eeeeec'>Swift_Mime_ContentEncoder_NativeQpContentEncoder->encodeString(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/ContentEncoder/QpContentEncoderProxy.php' bgcolor='#eeeeec'>.../QpContentEncoderProxy.php<b>:</b>87</td></tr>
			<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>0.0217</td><td bgcolor='#eeeeec' align='right'>1315160</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.quoted-printable-encode' target='_new'>quoted_printable_encode</a>
					(  )</td><td title='/home/kkeller13/public_html/bread-basket/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/ContentEncoder/NativeQpContentEncoder.php' bgcolor='#eeeeec'>.../NativeQpContentEncoder.php<b>:</b>95</td></tr>
		</table></font>
</body>
</html>